import type { Metadata } from "next";
import "./globals.css";
import { Inter, Poppins, Outfit, Barlow_Condensed } from "next/font/google";
import { Toaster } from "react-hot-toast";
import { ContextProvider } from "@/context/MyContext";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap",
});

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-poppins",
});

const outfit = Outfit({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  variable: "--font-outfit",
});

const barlow = Barlow_Condensed({
  subsets: ["latin"],
  weight: ["400", "600", "700"],
  variable: "--font-barlow",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`
        ${inter.variable}
        ${poppins.variable}
        ${outfit.variable}
        ${barlow.variable}
        bg-background!
      `}
      >
        <ContextProvider>
          {children}
          <Toaster position="top-center" reverseOrder={false} />
        </ContextProvider>
      </body>
    </html>
  );
}
