events {
    worker_connections 1024;
}

http {
    upstream nextjs_client {
        server client:3000;
    }

    upstream express_api {
        server server:8000;
    }

    server {
        listen 80;

        # 1. Routing cho Next.js Frontend
        location / {
            proxy_pass http://nextjs_client;
            proxy_set_header Host $host;
        }

        # 2. Routing cho Express API
        location /api/ {
            proxy_pass http://express_api;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # 3. Routing cho Socket.io
        location /socket.io/ {
            proxy_pass http://express_api;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "Upgrade";
        }
    }
}